apiVersion: v1
kind: Service
metadata:
  name: spring-to-do
spec:
  type: LoadBalancer
  selector:
    app: spring-to-do
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080